name: smart_daily_planner
description: A Smart Daily Planner app using advanced Flutter concepts.
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  expandable: ^5.0.1
  flutter_slidable: ^3.0.1
  fl_chart: ^0.63.0
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true